name: 'GitHub Actions Weather Bot'

on:
  watch:
    types: started
  schedule:
    - cron: '0 23 * * *'

jobs:
  bot:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout codes'
        uses: actions/checkout@v1
      - name: 'Get Weather'
        run: bash ./weather.sh
      - name: 'Get Date'
        run: echo "::set-env name=REPORT_DATE::$(TZ=':Asia/Chengdu' date '+%Y-%m-%d %T')"
      - name: 'Send mail'
        uses: dawidd6/action-send-mail@master
        with:
          server_address: smtp.126.com
          server_port: 465
          username: ${{ secrets.MAIL_USERNAME }}
          password: ${{ secrets.MAIL_PASSWORD }}
          subject: Chengdu Weather Report (${{env.REPORT_DATE}})
          body: file://result.html,file://email.txt
          to: 1971346995@qq.com
          from: GitHub Actions
          content_type: text/html